[colors.primary]
background = '#1f1d1d'
foreground = '#dababa'

[colors.cursor]
text   = '#1f1d1d'
cursor = '#dc8add'

[colors.selection]
text       = '#dababa'
background = '#696262'

[colors.normal]
black   = '#3a3333'
red     = '#f66151'
green   = '#dc8add'
yellow  = '#f666aa'
blue    = '#f66151'
magenta = '#f666aa'
cyan    = '#dababa'
white   = '#bc8c8c'

[colors.bright]
black   = '#2e2e2e'
red     = '#f66151'
green   = '#dc8add'
yellow  = '#f666aa'
blue    = '#dc8add'
magenta = '#f666aa'
cyan    = '#dababa'
white   = '#dababa'

[font]
size=12
#size = 12
#size = 10


[font.normal]
#family = "Jetbrains Mono"
family = "IoskeleyMono"
style = "normal"

[font.offset]
y=4


[window.padding]
x = 15
y = 15
